network:
  version: 2
  ethernets:
    enp65s0f0:
      match:
        macaddress: 14:02:ec:ca:e8:88
      dhcp4: false
      addresses: [10.100.1.1/24]
      set-name: pp1rdma
      mtu: 9000
    enp65s0f1:
      match:
        macaddress: 14:02:ec:ca:e8:89
      dhcp4: false
      addresses: [10.100.1.2/24]
      set-name: pp2rdma
      mtu: 9000
    enp65s0f2:
      match:
        macaddress: 14:02:ec:ca:e8:8a
      dhcp4: false
      addresses: [10.100.1.3/24]
      set-name: pp3rdma
      mtu: 9000
    enp65s0f3:
      match:
        macaddress: 14:02:ec:ca:e8:8b
      dhcp4: false
      addresses: [10.100.1.4/24]
      set-name: pp4rdma
      mtu: 9000
    enp65s0f4:
      match:
        macaddress: 14:02:ec:ca:e8:8c
      dhcp4: false
      set-name: pp1eth
      mtu: 9000
    enp65s0f5:
      match:
        macaddress: 14:02:ec:ca:e8:8d
      dhcp4: false
      set-name: pp2eth
      mtu: 9000
    enp65s0f6:
      match:
        macaddress: 14:02:ec:ca:e8:8e
      dhcp4: false
      set-name: pp3eth
      mtu: 9000
    enp65s0f7:
      match:
        macaddress: 14:02:ec:ca:e8:8f
      dhcp4: false
      set-name: pp4eth
      mtu: 9000
    enp1s0f0:
      match:
        macaddress: 14:02:ec:ca:e4:b4
      dhcp4: false
      addresses: [10.100.1.5/24]
      set-name: pp5rdma
      mtu: 9000
    enp1s0f1:
      match:
        macaddress: 14:02:ec:ca:e4:b5
      dhcp4: false
      addresses: [10.100.1.6/24]
      set-name: pp6rdma
      mtu: 9000
    enp1s0f2:
      match:
        macaddress: 14:02:ec:ca:e4:b6
      dhcp4: false
      addresses: [10.100.1.7/24]
      set-name: pp7rdma
      mtu: 9000
    enp1s0f3:
      match:
        macaddress: 14:02:ec:ca:e4:b7
      dhcp4: false
      addresses: [10.100.1.8/24]
      set-name: pp8rdma
      mtu: 9000
    enp1s0f4:
      match:
        macaddress: 14:02:ec:ca:e4:b8
      dhcp4: false
      set-name: pp5eth
      mtu: 9000
    enp1s0f5:
      match:
        macaddress: 14:02:ec:ca:e4:b9
      dhcp4: false
      set-name: pp6eth
      mtu: 9000
    enp1s0f6:
      match:
        macaddress: 14:02:ec:ca:e4:ba
      dhcp4: false
      set-name: pp7eth
      mtu: 9000
    enp1s0f7:
      match:
        macaddress: 14:02:ec:ca:e4:bb
      dhcp4: false
      set-name: pp8eth
      mtu: 9000
