network:
  version: 2
  ethernets:
    enp65s0f0:
      match:
        macaddress: 34:80:0d:bc:3d:d2
      dhcp4: false
      addresses: [10.100.3.1/24]
      set-name: pp1rdma
      mtu: 9000
    enp65s0f1:
      match:
        macaddress: 34:80:0d:bc:3d:d3
      dhcp4: false
      addresses: [10.100.3.2/24]
      set-name: pp2rdma
      mtu: 9000
    enp65s0f2:
      match:
        macaddress: 34:80:0d:bc:3d:d4
      dhcp4: false
      addresses: [10.100.3.3/24]
      set-name: pp3rdma
      mtu: 9000
    enp65s0f3:
      match:
        macaddress: 34:80:0d:bc:3d:d5
      dhcp4: false
      addresses: [10.100.3.4/24]
      set-name: pp4rdma
      mtu: 9000
    enp65s0f4:
      match:
        macaddress: 34:80:0d:bc:3d:d6
      dhcp4: false
      set-name: pp1eth
      mtu: 9000
    enp65s0f5:
      match:
        macaddress: 34:80:0d:bc:3d:d7
      dhcp4: false
      set-name: pp2eth
      mtu: 9000
    enp65s0f6:
      match:
        macaddress: 34:80:0d:bc:3d:d8
      dhcp4: false
      set-name: pp3eth
      mtu: 9000
    enp65s0f7:
      match:
        macaddress: 34:80:0d:bc:3d:d9
      dhcp4: false
      set-name: pp4eth
      mtu: 9000
    enp1s0f0:
      match:
        macaddress: 14:02:ec:ca:cd:f8
      dhcp4: false
      addresses: [10.100.3.5/24]
      set-name: pp5rdma
      mtu: 9000
    enp1s0f1:
      match:
        macaddress: 14:02:ec:ca:cd:f9
      dhcp4: false
      addresses: [10.100.3.6/24]
      set-name: pp6rdma
      mtu: 9000
    enp1s0f2:
      match:
        macaddress: 14:02:ec:ca:cd:fa
      dhcp4: false
      addresses: [10.100.3.7/24]
      set-name: pp7rdma
      mtu: 9000
    enp1s0f3:
      match:
        macaddress: 14:02:ec:ca:cd:fb
      dhcp4: false
      addresses: [10.100.3.8/24]
      set-name: pp8rdma
      mtu: 9000
    enp1s0f4:
      match:
        macaddress: 14:02:ec:ca:cd:fc
      dhcp4: false
      set-name: pp5eth
      mtu: 9000
    enp1s0f5:
      match:
        macaddress: 14:02:ec:ca:cd:fd
      dhcp4: false
      set-name: pp6eth
      mtu: 9000
    enp1s0f6:
      match:
        macaddress: 14:02:ec:ca:cd:fe
      dhcp4: false
      set-name: pp7eth
      mtu: 9000
    enp1s0f7:
      match:
        macaddress: 14:02:ec:ca:cd:ff
      dhcp4: false
      set-name: pp8eth
      mtu: 9000
