network:
  version: 2
  ethernets:
    enp65s0f0:
      match:
        macaddress: 14:02:ec:ca:e4:dc
      dhcp4: false
      addresses: [10.100.0.1/24]
      set-name: pp1rdma
      mtu: 9000
    enp65s0f1:
      match:
        macaddress: 14:02:ec:ca:e4:dd
      dhcp4: false
      addresses: [10.100.0.2/24]
      set-name: pp2rdma
      mtu: 9000
    enp65s0f2:
      match:
        macaddress: 14:02:ec:ca:e4:de
      dhcp4: false
      addresses: [10.100.0.3/24]
      set-name: pp3rdma
      mtu: 9000
    enp65s0f3:
      match:
        macaddress: 14:02:ec:ca:e4:df
      dhcp4: false
      addresses: [10.100.0.4/24]
      set-name: pp4rdma
      mtu: 9000
    enp65s0f4:
      match:
        macaddress: 14:02:ec:ca:e4:e0
      dhcp4: false
      set-name: pp1eth
      mtu: 9000
    enp65s0f5:
      match:
        macaddress: 14:02:ec:ca:e4:e1
      dhcp4: false
      set-name: pp2eth
      mtu: 9000
    enp65s0f6:
      match:
        macaddress: 14:02:ec:ca:e4:e2
      dhcp4: false
      set-name: pp3eth
      mtu: 9000
    enp65s0f7:
      match:
        macaddress: 14:02:ec:ca:e4:e3
      dhcp4: false
      set-name: pp4eth
      mtu: 9000
    enp1s0f0:
      match:
        macaddress: 14:02:ec:ca:e7:e8
      dhcp4: false
      addresses: [10.100.0.5/24]
      set-name: pp5rdma
      mtu: 9000
    enp1s0f1:
      match:
        macaddress: 14:02:ec:ca:e7:e9
      dhcp4: false
      addresses: [10.100.0.6/24]
      set-name: pp6rdma
      mtu: 9000
    enp1s0f2:
      match:
        macaddress: 14:02:ec:ca:e7:ea
      dhcp4: false
      addresses: [10.100.0.7/24]
      set-name: pp7rdma
      mtu: 9000
    enp1s0f3:
      match:
        macaddress: 14:02:ec:ca:e7:eb
      dhcp4: false
      addresses: [10.100.0.8/24]
      set-name: pp8rdma
      mtu: 9000
    enp1s0f4:
      match:
        macaddress: 14:02:ec:ca:e7:ec
      dhcp4: false
      set-name: pp5eth
      mtu: 9000
    enp1s0f5:
      match:
        macaddress: 14:02:ec:ca:e7:ed
      dhcp4: false
      set-name: pp6eth
      mtu: 9000
    enp1s0f6:
      match:
        macaddress: 14:02:ec:ca:e7:ee
      dhcp4: false
      set-name: pp7eth
      mtu: 9000
    enp1s0f7:
      match:
        macaddress: 14:02:ec:ca:e7:ef
      dhcp4: false
      set-name: pp8eth
      mtu: 9000
