network:
  version: 2
  ethernets:
    enp65s0f0:
      match:
        macaddress: 34:80:0d:bc:3b:a1
      dhcp4: false
      addresses: [10.100.4.1/24]
      set-name: pp1rdma
      mtu: 9000
    enp65s0f1:
      match:
        macaddress: 34:80:0d:bc:3b:a2
      dhcp4: false
      addresses: [10.100.4.2/24]
      set-name: pp2rdma
      mtu: 9000
    enp65s0f2:
      match:
        macaddress: 34:80:0d:bc:3b:a3
      dhcp4: false
      addresses: [10.100.4.3/24]
      set-name: pp3rdma
      mtu: 9000
    enp65s0f3:
      match:
        macaddress: 34:80:0d:bc:3b:a4
      dhcp4: false
      addresses: [10.100.4.4/24]
      set-name: pp4rdma
      mtu: 9000
    enp65s0f4:
      match:
        macaddress: 34:80:0d:bc:3b:a5
      dhcp4: false
      set-name: pp1eth
      mtu: 9000
    enp65s0f5:
      match:
        macaddress: 34:80:0d:bc:3b:a6
      dhcp4: false
      set-name: pp2eth
      mtu: 9000
    enp65s0f6:
      match:
        macaddress: 34:80:0d:bc:3b:a7
      dhcp4: false
      set-name: pp3eth
      mtu: 9000
    enp65s0f7:
      match:
        macaddress: 34:80:0d:bc:3b:a8
      dhcp4: false
      set-name: pp4eth
      mtu: 9000
    enp1s0f0:
      match:
        macaddress: 14:02:ec:ca:e5:04
      dhcp4: false
      addresses: [10.100.4.5/24]
      set-name: pp5rdma
      mtu: 9000
    enp1s0f1:
      match:
        macaddress: 14:02:ec:ca:e5:05
      dhcp4: false
      addresses: [10.100.4.6/24]
      set-name: pp6rdma
      mtu: 9000
    enp1s0f2:
      match:
        macaddress: 14:02:ec:ca:e5:06
      dhcp4: false
      addresses: [10.100.4.7/24]
      set-name: pp7rdma
      mtu: 9000
    enp1s0f3:
      match:
        macaddress: 14:02:ec:ca:e5:07
      dhcp4: false
      addresses: [10.100.4.8/24]
      set-name: pp8rdma
      mtu: 9000
    enp1s0f4:
      match:
        macaddress: 14:02:ec:ca:e5:08
      dhcp4: false
      set-name: pp5eth
      mtu: 9000
    enp1s0f5:
      match:
        macaddress: 14:02:ec:ca:e5:09
      dhcp4: false
      set-name: pp6eth
      mtu: 9000
    enp1s0f6:
      match:
        macaddress: 14:02:ec:ca:e5:0a
      dhcp4: false
      set-name: pp7eth
      mtu: 9000
    enp1s0f7:
      match:
        macaddress: 14:02:ec:ca:e5:0b
      dhcp4: false
      set-name: pp8eth
      mtu: 9000
