network:
  version: 2
  ethernets:
    enp65s0f0:
      match:
        macaddress: 34:80:0d:bc:3d:c1
      dhcp4: false
      addresses: [10.100.11.1/24]
      set-name: pp1rdma
      mtu: 9000
    enp65s0f1:
      match:
        macaddress: 34:80:0d:bc:3d:c2
      dhcp4: false
      addresses: [10.100.11.2/24]
      set-name: pp2rdma
      mtu: 9000
    enp65s0f2:
      match:
        macaddress: 34:80:0d:bc:3d:c3
      dhcp4: false
      addresses: [10.100.11.3/24]
      set-name: pp3rdma
      mtu: 9000
    enp65s0f3:
      match:
        macaddress: 34:80:0d:bc:3d:c4
      dhcp4: false
      addresses: [10.100.11.4/24]
      set-name: pp4rdma
      mtu: 9000
    enp65s0f4:
      match:
        macaddress: 34:80:0d:bc:3d:c5
      dhcp4: false
      set-name: pp1eth
      mtu: 9000
    enp65s0f5:
      match:
        macaddress: 34:80:0d:bc:3d:c6
      dhcp4: false
      set-name: pp2eth
      mtu: 9000
    enp65s0f6:
      match:
        macaddress: 34:80:0d:bc:3d:c7
      dhcp4: false
      set-name: pp3eth
      mtu: 9000
    enp65s0f7:
      match:
        macaddress: 34:80:0d:bc:3d:c8
      dhcp4: false
      set-name: pp4eth
      mtu: 9000
    enp1s0f0:
      match:
        macaddress: 14:02:ec:ca:e1:1c
      dhcp4: false
      addresses: [10.100.11.5/24]
      set-name: pp5rdma
      mtu: 9000
    enp1s0f1:
      match:
        macaddress: 14:02:ec:ca:e1:1d
      dhcp4: false
      addresses: [10.100.11.6/24]
      set-name: pp6rdma
      mtu: 9000
    enp1s0f2:
      match:
        macaddress: 14:02:ec:ca:e1:1e
      dhcp4: false
      addresses: [10.100.11.7/24]
      set-name: pp7rdma
      mtu: 9000
    enp1s0f3:
      match:
        macaddress: 14:02:ec:ca:e1:1f
      dhcp4: false
      addresses: [10.100.11.8/24]
      set-name: pp8rdma
      mtu: 9000
    enp1s0f4:
      match:
        macaddress: 14:02:ec:ca:e1:20
      dhcp4: false
      set-name: pp5eth
      mtu: 9000
    enp1s0f5:
      match:
        macaddress: 14:02:ec:ca:e1:21
      dhcp4: false
      set-name: pp6eth
      mtu: 9000
    enp1s0f6:
      match:
        macaddress: 14:02:ec:ca:e1:22
      dhcp4: false
      set-name: pp7eth
      mtu: 9000
    enp1s0f7:
      match:
        macaddress: 14:02:ec:ca:e1:23
      dhcp4: false
      set-name: pp8eth
      mtu: 9000
