network:
  version: 2
  ethernets:
    enp65s0f0:
      match:
        macaddress: 14:02:ec:ca:e7:c0
      dhcp4: false
      addresses: [10.100.2.1/24]
      set-name: pp1rdma
      mtu: 9000
    enp65s0f1:
      match:
        macaddress: 14:02:ec:ca:e7:c1
      dhcp4: false
      addresses: [10.100.2.2/24]
      set-name: pp2rdma
      mtu: 9000
    enp65s0f2:
      match:
        macaddress: 14:02:ec:ca:e7:c2
      dhcp4: false
      addresses: [10.100.2.3/24]
      set-name: pp3rdma
      mtu: 9000
    enp65s0f3:
      match:
        macaddress: 14:02:ec:ca:e7:c3
      dhcp4: false
      addresses: [10.100.2.4/24]
      set-name: pp4rdma
      mtu: 9000
    enp65s0f4:
      match:
        macaddress: 14:02:ec:ca:e7:c4
      dhcp4: false
      set-name: pp1eth
      mtu: 9000
    enp65s0f5:
      match:
        macaddress: 14:02:ec:ca:e7:c5
      dhcp4: false
      set-name: pp2eth
      mtu: 9000
    enp65s0f6:
      match:
        macaddress: 14:02:ec:ca:e7:c6
      dhcp4: false
      set-name: pp3eth
      mtu: 9000
    enp65s0f7:
      match:
        macaddress: 14:02:ec:ca:e7:c7
      dhcp4: false
      set-name: pp4eth
      mtu: 9000
    enp1s0f0:
      match:
        macaddress: 14:02:ec:ca:e5:2c
      dhcp4: false
      addresses: [10.100.2.5/24]
      set-name: pp5rdma
      mtu: 9000
    enp1s0f1:
      match:
        macaddress: 14:02:ec:ca:e5:2d
      dhcp4: false
      addresses: [10.100.2.6/24]
      set-name: pp6rdma
      mtu: 9000
    enp1s0f2:
      match:
        macaddress: 14:02:ec:ca:e5:2e
      dhcp4: false
      addresses: [10.100.2.7/24]
      set-name: pp7rdma
      mtu: 9000
    enp1s0f3:
      match:
        macaddress: 14:02:ec:ca:e5:2f
      dhcp4: false
      addresses: [10.100.2.8/24]
      set-name: pp8rdma
      mtu: 9000
    enp1s0f4:
      match:
        macaddress: 14:02:ec:ca:e5:30
      dhcp4: false
      set-name: pp5eth
      mtu: 9000
    enp1s0f5:
      match:
        macaddress: 14:02:ec:ca:e5:31
      dhcp4: false
      set-name: pp6eth
      mtu: 9000
    enp1s0f6:
      match:
        macaddress: 14:02:ec:ca:e5:32
      dhcp4: false
      set-name: pp7eth
      mtu: 9000
    enp1s0f7:
      match:
        macaddress: 14:02:ec:ca:e5:33
      dhcp4: false
      set-name: pp8eth
      mtu: 9000
